{aconv-chans: 16, aconv-filts: 5, adim: 16, atype: location, batch-size: 32, batch-sort-key: shuffle,
  bce-pos-weight: 1.0, cumulate-att-w: true, dlayers: 1, dropout-rate: 0.5, dunits: 16,
  econv-chans: 16, econv-filts: 5, econv-layers: 1, elayers: 1, embed-dim: 16, epochs: 5,
  eps: 1e-6, eunits: 16, lr: 1e-3, maxlen-in: 150, maxlen-out: 400, patience: 5, postnet-chans: 16,
  postnet-filts: 5, postnet-layers: 1, prenet-layers: 1, prenet-units: 16, reduction-factor: 5,
  report-interval-iters: 10, use-batch-norm: true, use-concate: true, use-masking: true,
  use-residual: false, weight-decay: 0.0, zoneout-rate: 0.1}
